### ISSUE TITLE
Example code for using neo4j-etl with Microsoft SQL Server on local Docker 

### ISSUE THREAD

**Issue by peternorbeck** [neo4j-contrib/neo4j-etl#3]
Hello,

I've had a discussion on the neo4j #help-import slack channel about using neo4j-etl to export data from a local Microsoft SQL Server running on a Docker.  With help from the great people there I got it working.  Because there ara lacking documentation about this I wrote some documentation about what I did that maybe could be useful for others.

My settings:
* OSX
* Docker installed
* neo4j-etl version `neo4j-etl-cli-1.2.0-BETA01`
* Java version: `1.8.0_131`
* Java $JAVA_HOME `/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home`
* Neo4j enterprise

#### 1. Setup Docker for Microsoft SQL Server 

create file: docker-compose.yml
```
version: "3"

services:
  mssql:
    image: microsoft/mssql-server-linux
    container_name: Test_Mssql_Server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password
    ports:
      - 1433:1433
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata:
```
Start docker with `$ docker-compose up`

#### 2. Import Northwind demo sql data to mssql db (or use your own)
 - Download Northwind.Ms.SQL.2005.sql from [here](https://code.google.com/archive/p/northwindextended/downloads)
- Import SQL to MsSQL  ( I used Aqua Data Studio)

#### 3. Download neo4j-etl
- [Download latest here](https://github.com/neo4j-contrib/neo4j-etl/releases)

#### 4. Install Microsoft SQL driver
- [Download here](https://www.microsoft.com/en-us/download/details.aspx?id=55539)
- Add driver .jar file (mssql-jdbc-6.2.2.jre8.jar) to /lib folder

#### Generate-metadata-mapping 

 ```
./bin/neo4j-etl generate-metadata-mapping \
  --rdbms:url "jdbc:sqlserver://localhost:1433;databaseName=Northwind" \
  --rdbms:user SA --rdbms:password Password \
  --rdbms:schema Northwind.dbo > ./mapping.json
```

#### Import to Neo4j database
Only tested with --using cypher:direct

```
./bin/neo4j-etl export \
 --rdbms:url "jdbc:sqlserver://localhost:1433;databaseName=Northwind" \
 --rdbms:user SA --rdbms:password Password --rdbms:schema Northwind.dbo \
 --using cypher:direct \
 --neo4j:url bolt://localhost:7687 --neo4j:user <neo4j-user> --neo4j:password <neo4j-pass> \
 --import-tool <path-to-neo4j-home>/bin \
 --csv-directory <path-to-neo4j-home>/import"
```
