### ISSUE TITLE
DATETIME values return a string with mysql and export using cypher:batch

### ISSUE THREAD

**Issue by vga91** [neo4j-contrib/neo4j-etl#98]
Create a docker-compose.yml
```
version: '3.8'

services:
  mysql:
    hostname: mysql
    image: mysql:8.0.31
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    networks:
      - my_network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: northwind
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
```

And a `mysql-dump/northwind.sql` file:
```
CREATE DATABASE IF NOT EXISTS northwind;
USE northwind;

CREATE TABLE `Employees` (
    `EmployeeID` INTEGER NOT NULL AUTO_INCREMENT,
    `BirthDate` DATETIME,
    CONSTRAINT `PK_Employees` PRIMARY KEY (`EmployeeID`)
);

TRUNCATE TABLE Employees;
INSERT INTO Employees VALUES(null,'1948-12-08');
```

And execute `docker-compose up -d`.

Then we can execute:
```
./bin/neo4j-etl generate-metadata-mapping --rdbms:url "jdbc:mysql://localhost:3306/northwind?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false" --rdbms:user root --rdbms:password rootpassword --rdbms:schema northwind --output-mapping-file /tmp/mapping.json --csv-directory /tmp/northwind
```

and finally:
```
./bin/neo4j-etl export \
 --rdbms:url "jdbc:mysql://localhost:3306/northwind?autoReconnect=true&useSSL=false" \
 --rdbms:user root --rdbms:password rootpassword \
 --rdbms:schema northwind --using cypher:batch \
 --csv-directory /tmp/northwind --mapping-file /tmp/mapping.json --neo4j:url "bolt://server2:7687" --neo4j:user neo4j --neo4j:password "mypassword" --debug --unwindBatchSize 1000 --txBatchSize 1000 --quote '"' --force
```

By executing `MATCH (n:Employee) RETURN valueType(n.birthDate)`,
we can see that the property `BirthDate` is returned as a string, instead of a `LOCAL DATETIME`
